FROM golang:latest

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

RUN apt-get update
RUN apt-get install git gcc

RUN mkdir -p "$GOPATH/src/github/sinfo/go-tutorial"
WORKDIR $GOPATH/src/github.com/sinfo/go-tutorial/
COPY . .

RUN go get -d -v ./...
RUN go get gotest.tools/assert
RUN go get -u github.com/mgechev/revive
RUN go install -v ./...

RUN go build -o main *.go

RUN go test -c ./routes
RUN chmod +x ./routes.test
RUN chmod +x ./run_tests.sh

RUN apt-get install -y mongodb
RUN mkdir data