version: '3.3'
services:
    api:
        build: 
            context: '.'
            dockerfile: './Dockerfile'
        container_name: 'go-tutorial'
        environment:
            - 'GO_TUTORIAL_DB_URL=mongodb://host.docker.internal:27017'
            - 'GO_TUTORIAL_DB_NAME=gotutorial'
    
    swaggerui:
        image: swaggerapi/swagger-ui
        environment:
            - 'SWAGGER_JSON=/var/www/swagger.json'
        volumes:
            - .:/var/www/
        links:
            - api
        depends_on:
            - 'api'

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
        links:
            - api
            - swaggerui
        depends_on:
            - 'api'
            - 'swaggerui'