version: '3.3'
services:
    sut:
        build:
            context: '.'
            dockerfile: Dockerfile_test
        ports:
            - '8000:8000'
        environment:
            - 'GO_TUTORIAL_DB_TEST_URL=mongodb://localhost:27017'
            - 'GO_TUTORIAL_DB_TEST_NAME=gotutorialtest'