version: '3.3'
services:
    sut:
        container_name: 'go-tutorial-test'
        depends_on:
            - 'db'
        build:
            context: '.'
            dockerfile: Dockerfile_test
        ports:
            - '8000:8000'
        environment:
            - 'GO_TUTORIAL_DB_TEST_URL=mongodb://host.docker.internal:27017'
            - 'GO_TUTORIAL_DB_TEST_NAME=gotutorialtest'
        command:
            - './run_tests.sh'
    db:
        image: mongo
        ports:
            - 27017:27017