version: '3.3'
services:
    sut:
        container_name: 'go-tutorial-test'
        build: '.'
        ports:
            - '8000:8000'
        environment:
            - 'GO_TUTORIAL_DB_URL=mongodb://host.docker.internal:27017'
            - 'GO_TUTORIAL_DB_NAME=gotutorialtest'
        depends_on:
            - mongo
        command:
            - './run_tests.sh'
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - data-volume:/data/db
volumes:
    data-volume: