#!/bin/sh

status=$?
if [ $status -ne 0 ]; then
  echo "Failed"
  exit $status
fi
echo "Done"

echo "\nTests"
for entry in `ls bin | grep .test`
  do
    testfile="bin/$entry"
    printf "  [$testfile] "

    if ! $testfile; then
      echo "Failed"
      exit 1
    fi
done

echo "\nRunning linter..."

golint $(go list ./...)

exit 0